import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const bookCafe = localFont({
  src: [
    {
      path: "./fonts/PF스타더스트 3.0.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/PF스타더스트 3.0 Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/PF스타더스트 3.0 ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-book-cafe",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${bookCafe.variable} antialiased`}>{children}</body>
    </html>
  );
}
